# Generated by Django 3.1.2 on 2020-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=30)),
                ('email_of_company', models.CharField(max_length=30)),
                ('password_of_company', models.CharField(max_length=20)),
                ('activation_code', models.CharField(max_length=30)),
            ],
        ),
    ]
