# Generated by Django 3.1.3 on 2020-12-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201115_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(max_length=10)),
                ('name_of_user', models.CharField(max_length=30)),
                ('email_of_user', models.CharField(max_length=30, unique=True)),
                ('password_of_user', models.CharField(max_length=20)),
                ('company_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companyinfo')),
            ],
        ),
    ]
