# Generated by Django 3.1.3 on 2020-12-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='company_info_id',
            new_name='company_id',
        ),
    ]
